/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmclient_free: (a: number, b: number) => void;
export const wasmclient_add_content: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmclient_call_stats: (a: number) => [number, number];
export const wasmclient_clock_stats: (a: number) => [number, number];
export const wasmclient_connect: (a: number, b: number, c: number) => [number, number];
export const wasmclient_give: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const wasmclient_is_open: (a: number) => number;
export const wasmclient_load_content: (a: number, b: number, c: number) => [number, number];
export const wasmclient_login: (a: number, b: number, c: number) => void;
export const wasmclient_modify_content: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmclient_modify_locale: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmclient_modify_visuals: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmclient_new: () => number;
export const wasmclient_place_loose: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasmclient_place_stack: (a: number, b: number, c: number, d: number) => void;
export const wasmclient_player_id: (a: number) => number;
export const wasmclient_player_soul_id: (a: number) => number;
export const wasmclient_pump: (a: number) => number;
export const wasmclient_render_region: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmclient_send_chat: (a: number, b: number, c: number) => void;
export const wasmclient_set_anchor: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasmclient_sub_stats: (a: number) => [number, number];
export const wasmclient_subscribe_chat: (a: number) => void;
export const wasmclient_take_chat: (a: number) => [number, number];
export const wasmclient_take_content_changed: (a: number) => [number, number];
export const wasmclient_upload_master: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc0f1032e2470c65c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h890d5c3a091e35f1: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
