; content/visuals/manifest/berry.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/berry/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::berry:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::berry>
    :neutral>
      @define>
        12 &texture array
        1_1.albedo.png &texture.0 set
        1_2.albedo.png &texture.1 set
        1_3.albedo.png &texture.2 set
        1_4.albedo.png &texture.3 set
        1_5.albedo.png &texture.4 set
        1_6.albedo.png &texture.5 set
        1_7.albedo.png &texture.6 set
        1_8.albedo.png &texture.7 set
        1_9.albedo.png &texture.8 set
        1_10.albedo.png &texture.9 set
        1_11.albedo.png &texture.10 set
        1_12.albedo.png &texture.11 set
