; content/visuals/manifest/flora.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/flora/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::flora:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::flora>
    :neutral>
      @define>
        30 &texture array
        1_1.albedo.png &texture.0 set
        1_2.albedo.png &texture.1 set
        1_3.albedo.png &texture.2 set
        1_4.albedo.png &texture.3 set
        1_5.albedo.png &texture.4 set
        1_6.albedo.png &texture.5 set
        1_7.albedo.png &texture.6 set
        1_8.albedo.png &texture.7 set
        1_9.albedo.png &texture.8 set
        1_10.albedo.png &texture.9 set
        1_11.albedo.png &texture.10 set
        1_12.albedo.png &texture.11 set
        1_13.albedo.png &texture.12 set
        2_1.albedo.png &texture.13 set
        2_2.albedo.png &texture.14 set
        2_3.albedo.png &texture.15 set
        2_4.albedo.png &texture.16 set
        2_5.albedo.png &texture.17 set
        2_6.albedo.png &texture.18 set
        2_7.albedo.png &texture.19 set
        2_8.albedo.png &texture.20 set
        2_9.albedo.png &texture.21 set
        2_10.albedo.png &texture.22 set
        2_11.albedo.png &texture.23 set
        2_12.albedo.png &texture.24 set
        2_13.albedo.png &texture.25 set
        2_14.albedo.png &texture.26 set
        2_15.albedo.png &texture.27 set
        2_16.albedo.png &texture.28 set
        2_17.albedo.png &texture.29 set
