; content/visuals/manifest/flora.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/flora.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::flora>
    @define>
        0 &biomes array
    :neutral>
      @define>
        2 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
