; content/visuals/manifest/objects.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/objects.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::objects>
    @define>
        0 &biomes array
    :berry>
      @define>
        12 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :conifer>
      @define>
        9 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :deciduous>
      @define>
        7 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :flora>
      @define>
        30 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :flower>
      @define>
        28 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :mushroom>
      @define>
        23 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :stone>
      @define>
        18 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
