; content/visuals/manifest/requisite.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/requisite/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::requisite:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::requisite>
    :neutral>
      @define>
        35 &texture array
        1_1.albedo.png &texture.0 set
        1_2.albedo.png &texture.1 set
        1_3.albedo.png &texture.2 set
        1_4.albedo.png &texture.3 set
        1_5.albedo.png &texture.4 set
        1_6.albedo.png &texture.5 set
        1_7.albedo.png &texture.6 set
        1_8.albedo.png &texture.7 set
        1_9.albedo.png &texture.8 set
        1_10.albedo.png &texture.9 set
        1_11.albedo.png &texture.10 set
        2_1.albedo.png &texture.11 set
        3_1.albedo.png &texture.12 set
        3_2.albedo.png &texture.13 set
        3_3.albedo.png &texture.14 set
        3_4.albedo.png &texture.15 set
        3_5.albedo.png &texture.16 set
        4_1.albedo.png &texture.17 set
        5_1.albedo.png &texture.18 set
        5_2.albedo.png &texture.19 set
        5_3.albedo.png &texture.20 set
        5_4.albedo.png &texture.21 set
        5_5.albedo.png &texture.22 set
        5_6.albedo.png &texture.23 set
        5_7.albedo.png &texture.24 set
        5_8.albedo.png &texture.25 set
        5_9.albedo.png &texture.26 set
        5_10.albedo.png &texture.27 set
        5_11.albedo.png &texture.28 set
        5_12.albedo.png &texture.29 set
        5_13.albedo.png &texture.30 set
        5_14.albedo.png &texture.31 set
        5_15.albedo.png &texture.32 set
        5_16.albedo.png &texture.33 set
        6_1.albedo.png &texture.34 set
