; content/visuals/manifest/requisite.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/textures/master/requisite.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints),
; &hash (master version), &maps (bit0 albedo|bit1 normal|bit2 emissive).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::requisite>
    @define>
        0 &biomes array
    :axe>
      @define>
        1 &parts set
        3397319613940888 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        8 &var_count.0 set
        0 &factions array
    :brick>
      @define>
        1 &parts set
        772977897038550 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        11 &var_count.0 set
        0 &factions array
    :coal>
      @define>
        1 &parts set
        118806167764170 &hash set
        3 &maps set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        4 &var_count.0 set
        0 &factions array
    :dirt>
      @define>
        1 &parts set
        2699106225783032 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        5 &var_count.0 set
        0 &factions array
    :dust>
      @define>
        1 &parts set
        2436932811885678 &hash set
        3 &maps set
        16 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        1 &var_id.15 set
        16 &var_count array
        1 &var_count.0 set
        2 &var_count.1 set
        3 &var_count.2 set
        4 &var_count.3 set
        5 &var_count.4 set
        6 &var_count.5 set
        7 &var_count.6 set
        8 &var_count.7 set
        9 &var_count.8 set
        10 &var_count.9 set
        11 &var_count.10 set
        12 &var_count.11 set
        13 &var_count.12 set
        14 &var_count.13 set
        15 &var_count.14 set
        16 &var_count.15 set
        0 &factions array
    :food>
      @define>
        1 &parts set
        3305067663377923 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        3 &var_count.0 set
        0 &factions array
    :gravel>
      @define>
        1 &parts set
        1943833855002329 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        4 &var_count.0 set
        0 &factions array
    :herb>
      @define>
        1 &parts set
        2532555729017400 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        7 &var_count.0 set
        0 &factions array
    :ingot>
      @define>
        1 &parts set
        363889318638067 &hash set
        3 &maps set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        3 &var_count.0 set
        0 &factions array
    :log>
      @define>
        1 &parts set
        547494164047547 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :lumber>
      @define>
        1 &parts set
        2944900239591846 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        10 &var_count.0 set
        0 &factions array
    :ore>
      @define>
        1 &parts set
        1845099201689496 &hash set
        3 &maps set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        2 &var_count.0 set
        0 &factions array
    :phial.glass>
      @define>
        2 &parts set
        2701723786409986 &hash set
        3 &maps set
        16 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        1 &var_id.15 set
        16 &var_count array
        1 &var_count.0 set
        2 &var_count.1 set
        3 &var_count.2 set
        4 &var_count.3 set
        5 &var_count.4 set
        6 &var_count.5 set
        7 &var_count.6 set
        8 &var_count.7 set
        9 &var_count.8 set
        10 &var_count.9 set
        11 &var_count.10 set
        12 &var_count.11 set
        13 &var_count.12 set
        14 &var_count.13 set
        15 &var_count.14 set
        16 &var_count.15 set
        0 &factions array
    :pickaxe>
      @define>
        1 &parts set
        3319781568960461 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        9 &var_count.0 set
        0 &factions array
    :reliquary>
      @define>
        1 &parts set
        4088123966630712 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :rock>
      @define>
        1 &parts set
        2895771960839917 &hash set
        3 &maps set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        5 &var_count.0 set
        0 &factions array
    :sand>
      @define>
        1 &parts set
        70951438192333 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        6 &var_count.0 set
        0 &factions array
    :stick>
      @define>
        1 &parts set
        4467419164384522 &hash set
        3 &maps set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :stone>
      @define>
        1 &parts set
        2370569698558602 &hash set
        3 &maps set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        2 &var_count.0 set
        0 &factions array
