; content/visuals/manifest/requisite.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/textures/master/requisite.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::requisite>
    @define>
        0 &biomes array
    :axe>
      @define>
        1 &parts set
        95627546694172 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        8 &var_count.0 set
        0 &factions array
    :brick>
      @define>
        1 &parts set
        3778163958834951 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        11 &var_count.0 set
        0 &factions array
    :coal>
      @define>
        1 &parts set
        128958713086773 &hash set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        4 &var_count.0 set
        0 &factions array
    :dirt>
      @define>
        1 &parts set
        1438223516447581 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        5 &var_count.0 set
        0 &factions array
    :dust>
      @define>
        1 &parts set
        159011947634735 &hash set
        16 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        1 &var_id.15 set
        16 &var_count array
        1 &var_count.0 set
        2 &var_count.1 set
        3 &var_count.2 set
        4 &var_count.3 set
        5 &var_count.4 set
        6 &var_count.5 set
        7 &var_count.6 set
        8 &var_count.7 set
        9 &var_count.8 set
        10 &var_count.9 set
        11 &var_count.10 set
        12 &var_count.11 set
        13 &var_count.12 set
        14 &var_count.13 set
        15 &var_count.14 set
        16 &var_count.15 set
        0 &factions array
    :food>
      @define>
        1 &parts set
        1738255012333821 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        3 &var_count.0 set
        0 &factions array
    :gravel>
      @define>
        1 &parts set
        3207551142990921 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        4 &var_count.0 set
        0 &factions array
    :herb>
      @define>
        1 &parts set
        3297740997992374 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        7 &var_count.0 set
        0 &factions array
    :ingot>
      @define>
        1 &parts set
        2873188407090682 &hash set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        3 &var_count.0 set
        0 &factions array
    :log>
      @define>
        1 &parts set
        1503824728346111 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :lumber>
      @define>
        1 &parts set
        1796925896056366 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        10 &var_count.0 set
        0 &factions array
    :ore>
      @define>
        1 &parts set
        2305670533886955 &hash set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        2 &var_count.0 set
        0 &factions array
    :phial.glass>
      @define>
        2 &parts set
        2352900720063846 &hash set
        16 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        1 &var_id.15 set
        16 &var_count array
        1 &var_count.0 set
        2 &var_count.1 set
        3 &var_count.2 set
        4 &var_count.3 set
        5 &var_count.4 set
        6 &var_count.5 set
        7 &var_count.6 set
        8 &var_count.7 set
        9 &var_count.8 set
        10 &var_count.9 set
        11 &var_count.10 set
        12 &var_count.11 set
        13 &var_count.12 set
        14 &var_count.13 set
        15 &var_count.14 set
        16 &var_count.15 set
        0 &factions array
    :pickaxe>
      @define>
        1 &parts set
        4184281218205658 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        9 &var_count.0 set
        0 &factions array
    :reliquary>
      @define>
        1 &parts set
        1139253120111913 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :rock>
      @define>
        1 &parts set
        3148101295217022 &hash set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        5 &var_count.0 set
        0 &factions array
    :sand>
      @define>
        1 &parts set
        847166483882260 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        6 &var_count.0 set
        0 &factions array
    :stick>
      @define>
        1 &parts set
        3676113626633526 &hash set
        1 &var_id array
        2 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :stone>
      @define>
        1 &parts set
        3642801689069171 &hash set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        2 &var_count.0 set
        0 &factions array
