; content/visuals/manifest/soul_white.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/soul_white/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::soul_white:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::soul_white>
    :chord>
      @define>
        16 &texture array
        1_1.albedo.png &texture.0 set
        1_2.albedo.png &texture.1 set
        1_3.albedo.png &texture.2 set
        1_4.albedo.png &texture.3 set
        1_5.albedo.png &texture.4 set
        1_6.albedo.png &texture.5 set
        1_7.albedo.png &texture.6 set
        1_8.albedo.png &texture.7 set
        1_9.albedo.png &texture.8 set
        1_10.albedo.png &texture.9 set
        1_11.albedo.png &texture.10 set
        1_12.albedo.png &texture.11 set
        1_13.albedo.png &texture.12 set
        1_14.albedo.png &texture.13 set
        1_15.albedo.png &texture.14 set
        1_16.albedo.png &texture.15 set
    :chorus>
      @define>
        16 &texture array
        1_1.albedo.png &texture.0 set
        1_2.albedo.png &texture.1 set
        1_3.albedo.png &texture.2 set
        1_4.albedo.png &texture.3 set
        1_5.albedo.png &texture.4 set
        1_6.albedo.png &texture.5 set
        1_7.albedo.png &texture.6 set
        1_8.albedo.png &texture.7 set
        1_9.albedo.png &texture.8 set
        1_10.albedo.png &texture.9 set
        1_11.albedo.png &texture.10 set
        1_12.albedo.png &texture.11 set
        1_13.albedo.png &texture.12 set
        1_14.albedo.png &texture.13 set
        1_15.albedo.png &texture.14 set
        1_16.albedo.png &texture.15 set
    :resonance>
      @define>
        16 &texture array
        1_1.albedo.png &texture.0 set
        1_2.albedo.png &texture.1 set
        1_3.albedo.png &texture.2 set
        1_4.albedo.png &texture.3 set
        1_5.albedo.png &texture.4 set
        1_6.albedo.png &texture.5 set
        1_7.albedo.png &texture.6 set
        1_8.albedo.png &texture.7 set
        1_9.albedo.png &texture.8 set
        1_10.albedo.png &texture.9 set
        1_11.albedo.png &texture.10 set
        1_12.albedo.png &texture.11 set
        1_13.albedo.png &texture.12 set
        1_14.albedo.png &texture.13 set
        1_15.albedo.png &texture.14 set
        1_16.albedo.png &texture.15 set
