; content/visuals/manifest/soul.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/soul.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::soul>
    @define>
        0 &biomes array
    :golem.blueprint>
      @define>
        16 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :golem>
      @define>
        9 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :human.blueprint>
      @define>
        16 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :human>
      @define>
        16 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :undead.blueprint>
      @define>
        16 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :undead>
      @define>
        16 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
