; content/visuals/manifest/structure.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/textures/master/structure.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::structure>
    @define>
        0 &biomes array
    :alter>
      @define>
        1 &parts set
        6 &var_id array
        1 &var_id.0 set
        2 &var_id.1 set
        3 &var_id.2 set
        4 &var_id.3 set
        5 &var_id.4 set
        6 &var_id.5 set
        6 &var_count array
        1 &var_count.0 set
        1 &var_count.1 set
        1 &var_count.2 set
        1 &var_count.3 set
        1 &var_count.4 set
        1 &var_count.5 set
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :fountain>
      @define>
        1 &parts set
        10 &var_id array
        1 &var_id.0 set
        2 &var_id.1 set
        3 &var_id.2 set
        4 &var_id.3 set
        5 &var_id.4 set
        6 &var_id.5 set
        7 &var_id.6 set
        8 &var_id.7 set
        9 &var_id.8 set
        10 &var_id.9 set
        10 &var_count array
        1 &var_count.0 set
        1 &var_count.1 set
        1 &var_count.2 set
        1 &var_count.3 set
        1 &var_count.4 set
        1 &var_count.5 set
        1 &var_count.6 set
        1 &var_count.7 set
        1 &var_count.8 set
        1 &var_count.9 set
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :mirror>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :rack.weapon>
      @define>
        1 &parts set
        1 &var_id array
        4 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :soul.store>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :table.slab>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
