; content/visuals/manifest/structure.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/structure.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::structure>
    @define>
        0 &biomes array
    :alter>
      @define>
        6 &parts set
        0 &var_id array
        0 &var_count array
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :fountain>
      @define>
        10 &parts set
        0 &var_id array
        0 &var_count array
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :mirror>
      @define>
        1 &parts set
        0 &var_id array
        0 &var_count array
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :rack.weapon>
      @define>
        1 &parts set
        0 &var_id array
        0 &var_count array
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :soul.store>
      @define>
        1 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :table.slab>
      @define>
        1 &parts set
        0 &var_id array
        0 &var_count array
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
