; content/visuals/manifest/symbols.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/textures/master/symbols.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::symbols>
    @define>
        0 &biomes array
    :aether>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        8 &var_count.0 set
        0 &factions array
    :aether.black>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        4 &var_count.0 set
        0 &factions array
    :anima>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        5 &var_count.0 set
        0 &factions array
    :anima.black>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        1 &var_count.0 set
        0 &factions array
    :corpus>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        7 &var_count.0 set
        0 &factions array
    :corpus.black>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        3 &var_count.0 set
        0 &factions array
    :sollertia>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        6 &var_count.0 set
        0 &factions array
    :sollertia.black>
      @define>
        1 &parts set
        1 &var_id array
        1 &var_id.0 set
        1 &var_count array
        2 &var_count.0 set
        0 &factions array
