; content/visuals/manifest/tiles.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/view/public/textures/master/tiles.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::tiles>
    @define>
        0 &biomes array
    :concrete>
      @define>
        1 &parts set
        0 &var_id array
        0 &var_count array
        3 &factions array
        1 &factions.0 set
        2 &factions.1 set
        3 &factions.2 set
    :fog>
      @define>
        16 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
    :grass>
      @define>
        16 &parts set
        0 &var_id array
        0 &var_count array
        0 &factions array
